api_keys:
  binom: 130000018e09719a5c63999714101de82c18286d
  push_house: aed89d56233d3afa4655852324cdf12b

binom_urls:
  campaigns: https://bin.mapletrack.com/aaa.php?page=Stats&ts_id=29&date=12&group1=282&group2=1&group3=1&date_s=[DATE_S]&date_e=[DATE_E]&timezone=+3:00
  sources: https://bin.mapletrack.com/aaa.php?page=Stats&ts_id=29&date=12&group1=282&group2=27&group3=1&date_s=[DATE_S]&date_e=[DATE_E]&timezone=+3:00

push_house_urls:
  stats: https://push.house/api/statistics/

logging:
  format: '%(asctime)s [%(levelname)s] (%(threadName)s, IN %(funcName)s): %(message)s.'
  date_format: '%H:%M:%S %d.%m.%y'