binom_urls:
  traffic_sources: '[BINOM_URL]aaa.php?page=Traffic_Sources'
  ph_campaigns: '[BINOM_URL]aaa.php?page=Stats&ts_id=[TS_ID]&date=12&group1=282&group2=1&group3=1&date_s=[DATE_S]&date_e=[DATE_E]&timezone=+3:00'
  ph_sources: '[BINOM_URL]aaa.php?page=Stats&ts_id=[TS_ID]&date=12&group1=282&group2=27&group3=1&date_s=[DATE_S]&date_e=[DATE_E]&timezone=+3:00&val_page=All'
  ungads_campaigns: '[BINOM_URL]aaa.php?page=Stats&ts_id=[TS_ID]&date=12&group1=288&group2=1&group3=1&date_s=[DATE_S]&date_e=[DATE_E]&timezone=+3:00'
  ungads_sources: '[BINOM_URL]aaa.php?page=Stats&ts_id=[TS_ID]&date=12&group1=288&group2=27&group3=1&date_s=[DATE_S]&date_e=[DATE_E]&timezone=+3:00&val_page=All'

push_house_urls:
  stats: https://push.house/api/statistics/
  campaign_action: https://push.house/api/active/
  source_action: https://push.house/api/lists/

ungads_urls:
  stats: https://ungads.com/api/[API_KEY]/statistics
  campaign_action: https://ungads.com/api/[API_KEY]/campaign/[CAMPAIGN_ID]
  campaign_status: https://ungads.com/api/[API_KEY]/get-campaigns-by-id
  source_white: https://ungads.com/api/[API_KEY]/campaign/[CAMPAIGN_ID]/white-list
  source_black: https://ungads.com/api/[API_KEY]/campaign/[CAMPAIGN_ID]/black-list

logging:
  format: '%(asctime)s [%(levelname)s] (%(threadName)s, IN %(funcName)s): %(message)s.'
  date_format: '%H:%M:%S %d.%m.%y'

  file_format: '%(asctime)s - %(message)s.'
  file_date_format: '%H:%M:%S - %d.%m.%y'